### ISSUE TITLE
Bad certificate for conan.bintray.com 

### ISSUE THREAD

**Issue by rodolfoap** [conan-io/website#254]
I don't know where to post this, but since this is related to the https service, I will add it here.

Since a couple of hours (Mon 12 Apr 2021 10:00:00 AM CEST), conan-center is not functional, apparently the certificate for this link https://conan.bintray.com/ is bad (just try opening the link in your browser). Is there any alternative?

Thanks in advanced.

**Comment by memsharded** [comment]
Hi @rodolfoap 

yes, this is known, Bintray is closing. Please follow the issue here: https://github.com/conan-io/conan/issues/8788 (I will close this one as duplicated)

You will find there links to the blog posts, this has been announced since some time ago. Today we are migrating/testing some things, so disruptions are expected. Thanks for reporting!
