### ISSUE TITLE
No link to list of all packages on main page

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/website#3]
As in the title, there is no single link to a list of all publicly available packages or recipes on the main page of Conan.  It seems strange for a package manager to not include what packages it offers. I remember there was a link to conan-center before site redesign.

After reading the page more closely, one can find two links buried below among other links in the description of community, but to a person who isn't familiar with Conan looking at the names alone won't tell much - "conan-center" and "Bincrafters repository". And most people scan the page quickly for familiar keywords, they don't want to read everything.

**Comment by helmesjo** [comment]
Agree. Even googling _[conan c++ packages](http://www.google.com/search?q=conan+c%2B%2B+packages)_ gives nothing really useful, especially for new users. 

IMO one would expect the main [conan.io](https://conan.io/) to have anoverly pronounced "**Find packages**" button/search field, preferably defaulting to (and allowing to filter on) a few common repositories like the official & moderated [conan-center](https://bintray.com/conan/conan-center), [bincrafters public-conan](https://api.bintray.com/conan/bincrafters/public-conan) or [conan-community](https://bintray.com/conan-community/conan) (with short descriptions similar to those available [here](http://docs.conan.io/en/latest/uploading_packages/remotes.html) so that the implications/risks of each repository are obvious).

As a real life example, I've pitched conan at work and people are very positive, but then I get the obvious question "Does it have that package" and it takes me way too long to confidently give an answer...

**Comment by danimtb** [comment]
Some time ago, we included a button to conan-center where all the packages are uploaded for the community:

![image](https://user-images.githubusercontent.com/10808592/65870656-fd803b00-e37c-11e9-8091-006ca644abac.png)

Also with conan-center-index now this should be easier in the future

**Comment by prince-chrismc** [comment]
This has been available for a while so I am closing it

PS is there on the new design for 2.0 

![image](https://user-images.githubusercontent.com/16867443/223567162-c1b61368-c5e7-4839-9766-df4a8f177cf1.png)
